features(common): Latest Article Retrieval API [SEM-13]
Ditmar/api_sem_g1 pull request #2
Opened 2023-12-02 14:52 UTC by Evert5n

Latest Article Retrieval API [SEM-13] G1 display a list of updated articles with their title, abstract, publication date, and author. With GET

2023-12-05 04:20 UTC, Ditmar requested changes
Nice Job congratulations

2023-12-05 04:20 UTC, Ditmar commented on Dockerfile
> +CMD ["npm", "run", "start"]
Nice I forget update the code

2023-12-05 04:20 UTC, Ditmar commented on src/__mock__/mock-data.ts
> +export default mockData;
beautiful

2023-12-05 04:20 UTC, Ditmar commented on src/presentation/routers/user-router.ts
> +            ? response.status(HttpStateCodes.OK).send('Successfully deleted user with id ${id}')
nice job but is better if you send a json object please use json instead send

2023-12-05 04:20 UTC, Ditmar commented on src/presentation/routers/user-router.ts
> +            ? response.status(HttpStateCodes.OK).send('Successfully deleted user with id ${id}')
Another very important thing isn't to hardcode the messages it is better to use a central place to set the message I explain very good that in this pr.
check it -> https://github.com/Ditmar/api_sem_g2/pull/2/files
![image](https://github.com/Ditmar/api_sem_g1/assets/317151/41230399-d3c6-43ce-ac1c-be3884aa98e6)

2023-12-07 02:05 UTC, Evert5n commented
The latest articles retrieval API [SEM-13] G1 (Correction in user-router.ts change .send to .json) displays a list of updated articles with their title, abstract, publication date and author. With GET

2023-12-11 22:32 UTC, Ditmar approved these changes

2023-12-13 01:27 UTC, merged